version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint-config-brightspace
    versions:
    - 0.11.0
    - 0.12.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
