name: CI
on: pull_request
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
      - name: Install dependencies
        run: |
          npm install
          npm install @web/test-runner-saucelabs --no-save
      - name: Lint
        run: npm run lint
      - name: Unit Tests (SauceLabs)
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_FEDERATION }}
          SAUCE_USERNAME: D2L_Federation
        run: npx web-test-runner --config web-test-runner.sauce.config.mjs --group default
